version: '3'

services:
  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8080:80"
    environment:
      PORT: 80 
      MODE: "prod"

  confluence-service:
    build:
      context: ./confluence-service
    environment:
      MODE: "prod"

  jira-service:
    build:
      context: ./jira-service
    environment:
      MODE: "prod"

  stats-service:
    build:
      context: ./stats-service
    environment:
      MODE: "prod"

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pages
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
