// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: jira.proto

package jira

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jql          string `protobuf:"bytes,1,opt,name=jql,proto3" json:"jql,omitempty"`
	JiraInstance string `protobuf:"bytes,2,opt,name=jiraInstance,proto3" json:"jiraInstance,omitempty"`
	JiraUsername string `protobuf:"bytes,3,opt,name=jiraUsername,proto3" json:"jiraUsername,omitempty"`
	JiraToken    string `protobuf:"bytes,4,opt,name=jiraToken,proto3" json:"jiraToken,omitempty"`
}

func (x *IssueReq) Reset() {
	*x = IssueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jira_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueReq) ProtoMessage() {}

func (x *IssueReq) ProtoReflect() protoreflect.Message {
	mi := &file_jira_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueReq.ProtoReflect.Descriptor instead.
func (*IssueReq) Descriptor() ([]byte, []int) {
	return file_jira_proto_rawDescGZIP(), []int{0}
}

func (x *IssueReq) GetJql() string {
	if x != nil {
		return x.Jql
	}
	return ""
}

func (x *IssueReq) GetJiraInstance() string {
	if x != nil {
		return x.JiraInstance
	}
	return ""
}

func (x *IssueReq) GetJiraUsername() string {
	if x != nil {
		return x.JiraUsername
	}
	return ""
}

func (x *IssueReq) GetJiraToken() string {
	if x != nil {
		return x.JiraToken
	}
	return ""
}

type IssuesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issues []*Issue `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	Total  int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *IssuesRes) Reset() {
	*x = IssuesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jira_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssuesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuesRes) ProtoMessage() {}

func (x *IssuesRes) ProtoReflect() protoreflect.Message {
	mi := &file_jira_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuesRes.ProtoReflect.Descriptor instead.
func (*IssuesRes) Descriptor() ([]byte, []int) {
	return file_jira_proto_rawDescGZIP(), []int{1}
}

func (x *IssuesRes) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *IssuesRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Issue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key      string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	TestType string `protobuf:"bytes,3,opt,name=testType,proto3" json:"testType,omitempty"`
}

func (x *Issue) Reset() {
	*x = Issue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jira_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_jira_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_jira_proto_rawDescGZIP(), []int{2}
}

func (x *Issue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Issue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Issue) GetTestType() string {
	if x != nil {
		return x.TestType
	}
	return ""
}

var File_jira_proto protoreflect.FileDescriptor

var file_jira_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6a, 0x69, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82, 0x01, 0x0a,
	0x08, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x71, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x71, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x6a,
	0x69, 0x72, 0x61, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6a, 0x69, 0x72, 0x61, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x6a, 0x69, 0x72, 0x61, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6a, 0x69, 0x72, 0x61, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x69, 0x72, 0x61, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6a, 0x69, 0x72, 0x61, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x41, 0x0a, 0x09, 0x49, 0x73, 0x73, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1e,
	0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06,
	0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x22, 0x45, 0x0a, 0x05, 0x49, 0x73, 0x73, 0x75, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x32, 0x2c, 0x0a, 0x04, 0x4a,
	0x69, 0x72, 0x61, 0x12, 0x24, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x73,
	0x12, 0x09, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x49, 0x73,
	0x73, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x65, 0x64, 0x61, 0x6e, 0x74, 0x77, 0x61,
	0x6e, 0x6b, 0x68, 0x61, 0x64, 0x65, 0x2f, 0x74, 0x73, 0x72, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6a, 0x69, 0x72, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_jira_proto_rawDescOnce sync.Once
	file_jira_proto_rawDescData = file_jira_proto_rawDesc
)

func file_jira_proto_rawDescGZIP() []byte {
	file_jira_proto_rawDescOnce.Do(func() {
		file_jira_proto_rawDescData = protoimpl.X.CompressGZIP(file_jira_proto_rawDescData)
	})
	return file_jira_proto_rawDescData
}

var file_jira_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_jira_proto_goTypes = []interface{}{
	(*IssueReq)(nil),  // 0: IssueReq
	(*IssuesRes)(nil), // 1: IssuesRes
	(*Issue)(nil),     // 2: Issue
}
var file_jira_proto_depIdxs = []int32{
	2, // 0: IssuesRes.issues:type_name -> Issue
	0, // 1: Jira.GetIssues:input_type -> IssueReq
	1, // 2: Jira.GetIssues:output_type -> IssuesRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jira_proto_init() }
func file_jira_proto_init() {
	if File_jira_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jira_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jira_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssuesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jira_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Issue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jira_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jira_proto_goTypes,
		DependencyIndexes: file_jira_proto_depIdxs,
		MessageInfos:      file_jira_proto_msgTypes,
	}.Build()
	File_jira_proto = out.File
	file_jira_proto_rawDesc = nil
	file_jira_proto_goTypes = nil
	file_jira_proto_depIdxs = nil
}
